proyecto_rancho/proyecto_rancho/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib import admin
from registro import views

urlpatterns = [

    #path("", TemplateView.as_view(template_name="index.html"),name="inicio"),
    path("", views.login_view, name="login"),
    path('admin/', admin.site.urls),
    path('registro/', include('registro.urls')),
    path('usuario/', include('usuarios.urls')),
    path("export/excel/", views.export_excel, name="export_excel"),
    path("export/pdf/", views.export_pdf, name="export_pdf"),
]

proyecto_rancho/registro/urls.py
from django.urls import path
from .views import *

app_name = 'registro_app'
urlpatterns = [
    path("", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path('registrar/', registrar, name='registro'),
    path('registro-exitoso/', registro_exitoso, name='registro_exitoso'),
    path('crear/', crear_registro, name='crear'),
    path('reporte-mensual/', reporte_mensual_view, name='reporte_mensual'),
    path('configurar-comidas/', config_comidas, name='config_comidas'),
    path('datatable/',registro_datatable,name='datatable'),
    path('activar-formulario/', activar_formulario, name='activar_formulario')
]

proyecto_rancho/usuarios/urls.py
from django.urls import path
from .views import *

app_name = 'usuario_app'
urlpatterns = [
    path('crear/', crear_usuario_view, name='crear_formulario'),
    path('crear-usuario/', crear_usuario, name='crear'),

]

proyecto_rancho/frontend/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}Proyecto Rancho{% endblock %}
    </title>
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        @import url(https://fonts.googleapis.com/css?family=Expletus+Sans:600);
/*==========SCALE-IN==========*/
@-webkit-keyframes scale-in {
     0%   {transform: scale(10, 10); opacity: 0;}
    100% {transform: scale(1, 1); opacity: 1;}
}

@keyframes scale-in {
    0%   {transform: scale(10, 10); opacity: 0;}
    100% {transform: scale(1, 1);  opacity: 1;}
}
/*==========ROLL-OUT==========*/
@-webkit-keyframes roll-out {
    0%   {width: 0;}
    100% {width: 100%; }
}
@keyframes roll-out {
    0%   {width: 0;}
    100% {width: 100%; }
}
body{
   background: #213726;
   color: #9da67a;
}
main{
  width: 100%;
  overflow: hidden;
  font-family: 'Expletus Sans', cursive;
}
.hero{
  width: 100%;
  height: auto;
  text-align: center;
  margin: 0 auto;
  background: #1a3027;
  position: relative; 
  color: #fff;
}

.hero h1{
  font-size: 3.5em;
  text-shadow: 2px 2px 5px #000;
  margin: auto;
  position: absolute; 
  top: 120px;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 1;
}
.hero p{
  font-size: 1.5em;
  text-shadow: 2px 2px 5px #000;
  margin: auto;
  position: absolute; 
  top: 220px;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 1;
}
.hero img{
  width: 100%;
  object-fit: cover;
}

#hero2{
  width: 350px;
}

.bar{
  width: 100%;
  height: 200px;
  background: -moz-linear-gradient(289deg, #a3a36d 0%, #a4a46e 36%, #a3a36d 100%);
  background: -webkit-linear-gradient(289deg, #a3a36d 0%, #a4a46e 36%, #a3a36d 100%);
  background: -ms-linear-gradient(289deg, #a3a36d 0%, #a4a46e 36%, #a3a36d 100%);
  background: linear-gradient(161deg, #a3a36d 0%, #a4a46e 36%, #a3a36d 100%);
  opacity: 0.3;
  position: absolute; 
  z-index: 0;
  left: 0;
  top: 90px;
  -ms-transform-origin: 100% 0%;
  -webkit-transform-origin: 100% 0%;
  transform-origin: 100% 0%;
  -webkit-animation: roll-out 1.2s ease-out ;
  -moz-animation: roll-out 1.2s ease-out ;
  animation: roll-out 1.2s ease-out ; 
}
.hero h1, .hero p{
  -webkit-animation: scale-in 1.3s ease-out;
  -moz-animation: scale-in 1.3s  ease-out;
  animation: scale-in 1.3s ease-out; 
}

footer{
  width: 100%;
  height: 100px;
  color:#fff;
  background-color: rgb(157, 166, 122, .2);
}

@media (max-width: 768px) {
  .hero{
    height: 50vw; 
  }
  .bar{
    height: 26vw;
    top: 10vw;
  }
  .hero h1{
    font-size: 8vw;
    top: 13vw;
  }
  .hero p{
    font-size: 3vw;
    top: 30vw;
  }
  .hero img{
    width: 50% !important;
  }
}

    </style>
    {% block styles %}
    
    {% endblock %}
</head>
<body>
    <main>
      <div class="hero">
          <h1>Batallón de Ingenieros de Montaña 5</h1>
          <p class="pt-md-3">Fortaleza - Templanza - Justicia - Prudencia</p>
          
          {% if data.hero %}
            <img src="{% static 'img/hero.jpeg' %}" />
          {% else %}
            <img id="hero2" src="{% static 'img/hero2.png' %}"/>
          {% endif %}
            
          <div class="bar">
          </div>
      </div>
      <div class="pt-4">
        {% block content %}
        {% endblock %}
      </div>
      
    </main>
    <footer class="mt-4">
      <div class="d-flex justify-content-center align-items-end h-100">
        <p class="text-center">Sistema Militar de Registros(Si.Mi.R) - Todos los derechos reservados</p>
      </div>
    </footer>
</body>

<!-- BOOTSTRAP -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<!-- JQUERY -->
<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
{% block scripts %}

{% endblock %}
    
</html>

proyecto_rancho/frontend/templates/crear_usuario.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Crear Usuario{% endblock %}

{% block content %}
    <div class="d-flex flex-column align-items-center container">
        <h2>Registrar Usuario</h2>
        {% if messages %}
            {% for message in messages %}
            <div class="bg-danger text-white p-2 rounded mb-3">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <form id="crearUsuarioForm" method="post" action="{% url 'usuario_app:crear' %}">
        {% csrf_token %}
        <div class="mb-3">
            <div>
                <label for="first_name">Nombre</label>
                <input class="form-control" type="text" id="first_name" name="first_name" required>
                <small id="smallFirstName" class="form-text text-danger"></small>
            </div>
            <div>
                <label for="last_name">Apellido</label>
                <input class="form-control" type="text" id="last_name" name="last_name" required>
                <small id="smallLastName" class="form-text text-danger"></small>
            </div>
            <div>
                <label for="dni">Documento</label>
                <input class="form-control" type="number" id="dni" name="dni" required min="1">
                <small id="smallDni" class="form-text text-danger"></small>
            </div>
            <div>
                <label for="casino">Casino</label>
                <select class="form-control" name="casino" id="casinoSelect">
                        <option value="" selected hidden>Seleccione un casino</option>
                    {% for casino in data.casinos %}
                        <option value="{{casino.id}}">{{casino.nombre}}</option>
                    {% endfor %}
                </select>
                <small id="smallCasino" class="form-text text-danger"></small>
            </div>
            <div>
                <label for="username">Nombre de Usuario</label>
                <input class="form-control" type="text" id="username" name="username" required>
                <small id="smallUsername" class="form-text text-danger"></small>
            </div>
            <div>
                <label for="password">Contraseña</label>
                <input class="form-control" type="password" id="password" name="password" required>
            </div>
            <div>
                <label for="password2">Confirmar Contraseña</label>
                <input class="form-control" type="password" id="password2" name="password2" required>
                <small id="smallPassword" class="form-text text-danger"></small>
            </div>

        </div>
        <div class="d-flex justify-content-between gap-2">
            <button id="crearUsuarioSubmit" class="btn btn-success" type="submit">Registrar</button>
            <a class="btn btn-danger" href="{% url 'login' %}">Cancelar</a>
        </div>
    </form>
    </div>
    
    {% if messages %}
    {% for message in messages %}
        <div>{{ message }}</div>
    {% endfor %}
    {% endif %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/validaciones.js' %}"></script>
{% endblock %}

proyecto_rancho/frontend/templates/index.html
<!DOCTYPE html>
<html>
<head><title>Inicio</title></head>
<body>
  <h2>Bienvenido {{ current_user.id }}</h2>
  <p><a href="{% url 'registro_app:registro'%}">Registrar Consumo</a></p>
  <p><a href="{% url 'registro_app:reporte_mensual' %}">Generar Reporte Mensual</a></p>
  <p><a href="{% url 'usuario_app:crear_formulario'%}">Crear Usuario</a></p>
  <p><a href="{% url 'login' %}">LOGIN TEMPORAL</a></p>
  <p><a href="">Cerrar Sesión</a></p>
</body>
</html>

proyecto_rancho/frontend/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
  <div class="d-flex flex-column align-items-center">
    <h2 h2>Iniciar sesión</h2>
    <form method="post"action="{% url 'registro_app:login' %}">
      {% csrf_token %}
      {% if messages %}
          {% for message in messages %}
              <div
                  class="mb-2 p-2 rounded text-white
                  {% if message.tags == 'error' %} bg-danger
                  {% elif message.tags == 'success' %} bg-success
                  {% else %} bg-info {% endif %}">
                  {{ message }}
              </div>
          {% endfor %}
      {% endif %}
      <label>Usuario:</label>
      <input name="username" class="form-control" required>
      <label>Contraseña:</label>
      <input name="password" type="password" class="form-control" required>
      <div class="d-flex justify-content-center">
        <button class="btn btn-success mt-2" type="submit">Iniciar sesión</button>
      </div>
    </form>
    <div class="text-center">
      <span class="text-center">________________ . ________________</span>
      <br>
      <span>Para anotarte necesitas <a href="{% url 'usuario_app:crear_formulario' %}">crear una cuenta</a>.</span>
    </div>
  </div>

{% endblock %}

proyecto_rancho/frontend/templates/registrar.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Registrar Consumo{% endblock %}


{% block styles %}
    <style>
        .btn-check:checked + .btn {
        background-color: var(--bs-primary);
        border: 0;
        }
    </style>
{% endblock %}
    
        
{% block content %}
<div class="d-flex flex-column align-items-center container">
        <h2>Registrar Consumo</h2>
        {% if messages %}
            {% for message in messages %}
            <div class="bg-danger text-white p-2 rounded">{{ message }}</div>
            {% endfor %}
        {% endif %}
            
        <form id="registroForm" method="post" action="{% url 'registro_app:crear' %}">
            {% csrf_token %}
            <div class="mb-3">
                <div>
                    <label for="first_name">Nombre</label>
                    <input class="form-control" type="text" id="first_name" name="nombre" required readonly value="{{ usuario.first_name }}">
                </div>
                <div>
                    <label for="last_name">Apellido</label>
                    <input class="form-control" type="text" id="last_name" name="apellido" required readonly value="{{ usuario.last_name }}">
                </div>
                <div>
                    <label for="dni">Documento</label>
                    <input class="form-control" type="text" id="dni" name="documento" required readonly value="{{ usuario.dni }}">
                </div>
                <div>
                    <label for="casino">Casino</label>
                    <select class="form-control" id="casino" disabled>
                        <option value="{{ usuario.casino.id }}">{{ usuario.casino }}</option>
                    </select>
                    <input type="hidden" name="casino" value="{{ usuario.casino.id }}">
                </div>
                {% if not data.no_habilitado %}
                    <div>
                        <label for="comida">Seleccione comidas</label>
                        <div class="d-flex justify-content-center gap-2 mt-2">
                            {% for comida in comidas %}
                                {% if comida.habilitado %}
                                    <input type="checkbox" class="btn-check" id="comida_{{ comida.id }}" 
                                    name="comida" value="{{ comida.id }}">
                                    <label class="btn btn-sm btn-secondary" for="comida_{{ comida.id }}">
                                        {{ comida }}
                                    </label>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <small id="smallComida" class="form-text text-danger"></small>
                    </div>
                {% endif %}
            </div>
            
            {% if data.no_habilitado %}
                <div class="d-flex flex-column align-items-center">
                    <h2>Formulario no disponible</h2>
                    <p>El formulario solo se encuentra disponible entre las 7 y 10 de la mañana.</p>
                    <a href="{% url 'registro_app:logout' %}" class="btn btn-danger">Cerrar sesión</a>
                </div>
            {% else %}
                <div class="d-flex justify-content-center gap-2">
                    <button id="registroSubmit" class="btn btn-success" type="submit">Confirmar</button>
                    <a class="btn btn-danger" href="{% url 'registro_app:logout' %}">Cancelar</a>
                </div>
            {% endif %}
        </form>
    
</div>
    

{% endblock %}

{% block scripts %}
    <script src="{% static 'js/validaciones.js' %}"></script>
{% endblock %}

proyecto_rancho/frontend/templates/registro_exitoso.html
{% extends 'base.html' %}

{% block title %}Registro Exitoso{% endblock %}

{% block content %}
<div class="d-flex flex-column align-items-center gap-2">
    <h2>Registro Exitoso</h2>
    <p>Gracias por registrar tu consumo. Tu sesión ha sido cerrada por seguridad.</p>
    <a href="{% url 'login' %}" class="btn btn-primary">Volver a la página de inicio de sesión</a>
</div>
{% endblock %}

proyecto_rancho/frontend/templates/reporte.html
<!DOCTYPE html>
<html>
<head><title>Reporte Mensual</title></head>
<body>
  <h2>Generar Reporte Mensual</h2>
  <form method="post">
    <button type="submit">📄 Generar PDF</button>
  </form>
  <p style="color:green;">{{ mensaje }}</p>
  {% if mensaje == "PDF generado correctamente." %}
    <p><a href="{{ url_for('descargar_pdf') }}">Descargar PDF</a></p>
  {% endif %}
  <p><a href="{{ url_for('home') }}">Volver al inicio</a></p>
</body>
</html>

proyecto_rancho/frontend/templates/reporte_mensual.html
{% extends 'base.html' %}
{% load static %} 
{% block title %}Registro de comidas{% endblock %}
{% block styles %}
<!-- DATATABLE -->
<link
    rel="stylesheet"
    href="//cdn.datatables.net/2.3.3/css/dataTables.dataTables.min.css"
/>
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">
<!-- FLATPICKR -->
<link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css"
/>
<!-- ESTILOS EXTRA -->
<style>
    .btn-check:checked + .btn {
        background-color: var(--bs-primary);
        color: #fff;
    }

    .btn-check:not(:checked) + .btn {
        background-color: var(--bs-secondary);
        color: #fff;
    }
    
    #registroTable {
        color: #9da67a;
        background-color: #1a3027;
    }
    .card {
        background-color: #213726;
        border: 5px solid #9da67a;
    }
    select {
        display: inline-block;
        width: 100%;
        padding: 0.5rem 2.25rem 0.5rem 0.75rem; /* espacio a derecha para el chevron */
        font-size: 1rem;
        font-weight: 600;
        line-height: 1.5;
        color: #9da67a;
        background-color: #213726;
        border: 1px solid #ced4da;
        border-radius: 0.375rem;
        -webkit-appearance: none; /* quitar apariencia nativa en Safari/Chrome */
        -moz-appearance: none;
        appearance: none;
        box-shadow: none;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        cursor: pointer;
    }
    select:hover {
        border-color: #9da67a;
    }
    /* Estilo base (similar a .form-control de Bootstrap) */
    .custom-control {
        display: block;
        width: 100%;
        padding: 0.5rem 2.25rem 0.5rem 0.75rem; /* espacio a derecha para el chevron */
        font-size: 1rem;
        line-height: 1.5;
        color: #9da67a; /* texto */
        background-color: #213726 !important; /* fondo */
        background-clip: padding-box;
        border: 1px solid #ced4da; /* borde */
        border-radius: 0.375rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        cursor: pointer;
    }

    .custom-control:hover {
        border-color: #9da67a;
    }

    /* Focus */
    .custom-control:focus {
        color: #9da67a;
        background-color: #213726;
        border-color: #86b7fe; /* borde azul */
        outline: 0;
        box-shadow: 0 0 0 0.2rem rgba(13, 110, 253, 0.25); /* glow */
    }
    .custom-control::-webkit-calendar-picker-indicator {
        filter: invert(30%) sepia(60%) saturate(500%) hue-rotate(180deg);
        cursor: pointer;
    }
    .flatpickr-calendar {
        background-color: #213726;
    }
    .flatpickr-months {
        background-color: #53725a;
        padding-bottom: 10px;
    }
    .flatpickr-day {
        color: #9da67a;
    }
    .prevMonthDay,
    .nextMonthDay {
        color: #9da67a46 !important;
    }
    .today,
    .flatpickr-current-month,
    .flatpickr-weekday,
    .flatpickr-prev-month,
    .flatpickr-next-month {
        color: #d8d8d8 !important;
    }
</style>
{% endblock %} 
{% block content %}
<div class="container">
    <div class="card">
        <div
            class="card-header d-md-flex justify-content-between align-items-center"
        >
            <div class="d-flex d-md-block flex-column align-items-center mb-2">
                <h2>Registro del {{data.fecha_hoy}}</h2>
                <small class="text-center">
                    Comidas habilitadas: <br class="d-md-none" />
                    {% for comida in data.comidas %} 
                        {% if comida.habilitado %}
                        <span class="badge rounded-pill bg-info"
                            >{{comida.nombre}}</span
                        >
                        {% endif %} 
                    {% endfor %}
                </small>
            </div>
            <div class="d-flex gap-2 justify-content-center">
                <button
                    type="button"
                    class="btn btn-secondary btn-sm"
                    data-bs-toggle="modal"
                    data-bs-target="#configModal"
                >
                    <i class="fa-solid fa-gear"></i> Configuración
                </button>
                <a
                    class="btn btn-danger btn-sm"
                    href="{% url 'registro_app:logout' %}"
                    ><i class="fa-solid fa-right-from-bracket"></i> Cerrar Sesión</a
                >
            </div>
        </div>
        <div class="card-body">
            <div>
                <div class="row mb-3">
                    <div class="col-md-4 mb-2">
                        <input
                            type="date"
                            id="filtroFecha"
                            class="custom-control"
                        />
                    </div>
                    <div class="col-md-4 mb-2">
                        <select id="filtroComida" class="col-12">
                            <option value="">-- Todas las comidas --</option>
                            {% for c in data.comidas %}
                            <option value="{{ c.id }}">{{ c.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-4 mb-2">
                        <select id="filtroCasino" class="col-12">
                            <option value="">-- Todos los casinos --</option>
                            {% for c in data.casinos %}
                            <option value="{{ c.id }}">{{ c.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div>
                <table
                    id="registroTable"
                    class="table"
                    data-url="{% url 'registro_app:datatable' %}"
                >
                    <thead>
                        <tr>
                            <th>Fecha y Hora</th>
                            <th>Apellido</th>
                            <th>Nombre</th>
                            <th>Documento</th>
                            <th>Casino</th>
                            <th>Comida</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- MODAL DE CONFIGURACION -->
<div class="modal" tabindex="-1" id="configModal">
    <div class="modal-dialog">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="modal-title">Configuraciones</h5>
                <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                ></button>
            </div>
            <div class="modal-body">
                <div class="d-flex justify-content-center">
                    <button id="btnActivar" data-url="{% url 'registro_app:activar_formulario' %}" data-activado="{{ data.form_activado }}"
                        {% if data.form_activado == True %}
                            class="btn btn-secondary" disabled
                        {% elif data.form_activado == False %}
                            class="btn btn-warning"
                        {% else %}
                            class="btn btn-success" disabled
                        {% endif %}
                    >
                        {% if data.form_activado == True %}
                            El formulario está activo hasta las {{ data.hora }}
                        {% elif data.form_activado == False %}
                            Activar formulario temporalmente
                        {% else %}
                            El formulario está disponible ahora mismo
                        {% endif %}
                    </button>
                </div>
                <form
                    action="{% url 'registro_app:config_comidas' %}"
                    method="post"
                >
                        <div>
                            <h4>Habilitar comidas</h4>
                            {% csrf_token %} 
                            
                            <div class="d-flex justify-content-center gap-2">
                                {% for comida in data.comidas %}
                                    <input type="checkbox" 
                                        class="btn-check" 
                                        id="comida_{{ comida.id }}" 
                                        name="comida" 
                                        value="{{ comida.id }}"
                                        {% if comida.habilitado %} checked {% endif %}>
                                    <label for="comida_{{ comida.id }}" 
                                        class="btn btn-sm {% if comida.habilitado %}btn-primary{% else %}btn-secondary{% endif %}">
                                        {{ comida }}
                                    </label>
                                {% endfor %}
                            </div>

                        </div>
            </div>
            <div class="modal-footer">
                <button
                    type="button"
                    class="btn btn-secondary"
                    data-bs-dismiss="modal"
                >
                    Cancelar
                </button>
                <button type="submit" class="btn btn-primary">
                    Guardar cambios
                </button>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock %} 
{% block scripts %}
<script src="{% static 'js/reactivar-formulario.js' %}"></script>
<!-- DATATABLE -->
<script src="//cdn.datatables.net/2.3.3/js/dataTables.min.js"></script>
<script src="{% static 'js/registros-datatable.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/responsive/3.0.7/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/buttons/3.2.5/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/3.2.5/js/buttons.html5.min.js"></script>
<!-- FLATPICKR -->
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/es.js"></script>
<script src="{% static 'js/registros-flatpickr.js' %}"></script>
<!-- FONTAWESOME -->
<script src="https://kit.fontawesome.com/06f507be24.js" crossorigin="anonymous"></script>
{% endblock %}